name: Deploy to cloudtype
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: rlawo32/dudu-project
          stage: main
          yaml: >
            name: dudu-project-be

            app: java@17

            options:
              ports: 8080
              env:
                - name: DB_URL
                  value: jdbc:mariadb://svc.sel5.cloudtype.app:30995/dudu_project
                - name: DB_NAME
                  value: root
                - name: DB_PASSWORD
                  value: root456321
                - name: AUTH_SECRET
                  value: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
                - name: AUTH_SECOND
                  value: "60000"
                - name: S3_ACCESS_KEY_ID
                  value: AKIA34GK4P4GQRP5JAVQ
                - name: S3_SECRET_KEY
                  value: 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
                - name: S3_BUCKET
                  value: react-project-bucket
                - name: GOOGLE_CLIENT_ID
                  value: 125179384425-fjcq36el4gni54a629p876mmmr15bt5f.apps.googleusercontent.com
                - name: GOOGLE_CLIENT_SECRET
                  value: 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
                - name: NAVER_CLIENT_ID
                  value: tDxT9LD_WM0dDak0wseg
                - name: NAVER_CLIENT_SECRET
                  value: ByB9PBdxn_
                - name: KAKAO_CLIENT_ID
                  value: e37f1380b6c56fb45f7f5a30860ab6c1
                - name: KAKAO_CLIENT_SECRET
                  value: FfJVyfpEimkYW1OZJJ6nxEzhA239vGnP
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
